blank_issues_enabled: false
contact_links:
  - name: Have a question? Just ask :)
    url: https://github.com/shcherbak-ai/contextgem/discussions/new/
    about: For questions or discussions that aren't bugs or feature requests
  - name: Documentation
    url: https://contextgem.dev
    about: Check the documentation for usage information and guides